apiVersion: batch/v1
kind: Job
metadata:
  name: setup
spec:
  template:
    metadata:
      name: setup
    spec:
      containers:
        - name: setup
          image: jsndh/webapp:ee4b573
          command: ["/bin/bash", "./setup.sh"]
          env:
          - name: PASSENGER_APP_ENV
            value: development
      restartPolicy: Never
